In [1]:
import pandas as pd
import numpy as np

In [2]:
#view the data
data = pd.read_csv("../data.csv",header=None)
print(data.shape)
data

(1085, 3121)

,0,1,2,3,4,5,6,7,8,9,...,3111,3112,3113,3114,3115,3116,3117,3118,3119,3120
0,750.271,750.094,750.380,750.726,750.890,750.860,749.192,748.599,749.077,749.605,...,0.132028,0.171277,0.167796,0.141710,0.154595,0.182266,0.167652,0.160940,0.130541,0
1,750.094,750.380,750.726,750.890,750.860,749.192,748.599,749.077,749.605,749.638,...,0.171277,0.167796,0.141710,0.154595,0.182266,0.167652,0.160940,0.130541,0.216049,0
2,750.380,750.726,750.890,750.860,749.192,748.599,749.077,749.605,749.638,750.009,...,0.167796,0.141710,0.154595,0.182266,0.167652,0.160940,0.130541,0.216049,0.173276,0
3,750.726,750.890,750.860,749.192,748.599,749.077,749.605,749.638,750.009,752.381,...,0.141710,0.154595,0.182266,0.167652,0.160940,0.130541,0.216049,0.173276,0.133951,0
4,750.890,750.860,749.192,748.599,749.077,749.605,749.638,750.009,752.381,754.066,...,0.154595,0.182266,0.167652,0.160940,0.130541,0.216049,0.173276,0.133951,0.180807,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1080,772.884,772.325,771.107,768.527,764.311,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1081,772.325,771.107,768.527,764.311,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1082,771.107,768.527,764.311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1083,768.527,764.311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1084,764.311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [3]:
#Make sure each column is numeric type
data.dtypes

0       float64
1       float64
2       float64
3       float64
4       float64
         ...
3116    float64
3117    float64
3118    float64
3119    float64
3120      int64
Length: 3121, dtype: object

In [86]:
data.iloc[:,-1].value_counts()

0    709
1    376
Name: 3120, dtype: int64

In [88]:
data.describe()

,0,1,2,3,4,5,6,7,8,9,...,3111,3112,3113,3114,3115,3116,3117,3118,3119,3120
count,1085.000000,1080.000000,1075.000000,1070.000000,1065.000000,1060.000000,1055.000000,1050.000000,1045.000000,1040.000000,...,930.000000,926.000000,922.000000,918.000000,914.000000,910.000000,906.000000,902.000000,898.000000,1085.000000
mean,949.630347,950.074679,950.504670,950.925650,951.334744,951.736049,952.140777,952.552810,952.969316,953.385981,...,0.269882,0.269925,0.269935,0.269905,0.269934,0.270047,0.270039,0.270056,0.270038,0.346544
std,175.704156,175.752354,175.811991,175.882825,175.959229,176.043643,176.126274,176.202935,176.269734,176.336773,...,0.138245,0.138463,0.138674,0.138923,0.139084,0.139250,0.139522,0.139738,0.139767,0.476088
min,649.828000,652.653000,654.781000,655.365000,655.673000,655.673000,661.210000,661.433000,663.127000,666.120000,...,0.073333,0.073333,0.073333,0.073333,0.073333,0.073333,0.073333,0.073333,0.073333,0.000000
25%,764.852000,764.809750,764.767500,764.725250,764.683000,764.672750,764.662500,764.652250,764.642000,764.633500,...,0.162295,0.162295,0.162247,0.162220,0.162220,0.162220,0.162111,0.161976,0.162111,0.000000
50%,1013.960000,1015.520000,1016.320000,1017.795000,1018.500000,1020.050000,1020.780000,1021.250000,1022.860000,1023.480000,...,0.231131,0.230771,0.230591,0.230469,0.230469,0.230469,0.229872,0.229872,0.229872,0.000000
75%,1113.190000,1113.695000,1113.780000,1114.952500,1115.460000,1115.537500,1115.635000,1115.702500,1115.880000,1116.505000,...,0.324014,0.324014,0.324014,0.324014,0.323832,0.323832,0.323832,0.323832,0.323832,1.000000
max,1236.410000,1236.410000,1236.410000,1236.410000,1236.410000,1236.410000,1236.410000,1236.410000,1236.410000,1236.410000,...,0.721438,0.721438,0.721438,0.721438,0.721438,0.721438,0.721438,0.721438,0.721438,1.000000

In [3]:
from sklearn.model_selection import train_test_split
col_nums = data.shape[1]
X = data.iloc[:,0:col_nums-1]
y = data.iloc[:,col_nums-1:col_nums]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state=1)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((759, 3120), (326, 3120), (759, 1), (326, 1))

## First try filling NA with a constant

In [8]:
X_train1 = X_train.fillna(-100000)

In [9]:
from sklearn import tree
from sklearn.model_selection import cross_val_score
clf = tree.DecisionTreeClassifier()
accuracy = cross_val_score(clf,X_train1,y_train,scoring="accuracy",cv=10)
print(f"Accuracy for each cv is:{accuracy}")
print("---------------------------")
print(f"Mean accuracy is {np.mean(accuracy)}")

Accuracy for each cv is:[0.62337662 0.74025974 0.68831169 0.79220779 0.72368421 0.69333333
 0.64       0.77333333 0.65333333 0.56      ]
---------------------------
Mean accuracy is 0.6887840054682159

In [10]:
#Accuracy on test set
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train1,y_train)
X_test1 = X_test.fillna(-100000)
y_pred = clf.predict(X_test1)
clf.score(X_test1,y_test)

0.7208588957055214

## Then we try filling NA with mean

In [11]:
X_train2 = X_train.apply(lambda x:x.fillna(x.mean()),axis=0)
y_train2 = y_train.fillna(np.mean(y_train))

In [12]:
X_train2

,0,1,2,3,4,5,6,7,8,9,...,3110,3111,3112,3113,3114,3115,3116,3117,3118,3119
776,1038.250,1040.980,1044.570,1046.320,1046.460,1047.940,1049.380,1048.210,1046.620,1045.400,...,0.257096,0.319871,0.320174,0.298875,0.239165,0.342722,0.323973,0.264083,0.279246,0.299938
891,1053.520,1051.170,1048.450,1047.660,1047.570,1046.850,1045.560,1044.360,1048.520,1048.480,...,0.332451,0.294353,0.289811,0.295243,0.215595,0.229206,0.289764,0.237811,0.359395,0.271250
107,772.199,771.667,769.927,769.533,768.172,766.430,764.088,759.084,756.426,752.864,...,0.142412,0.157996,0.153356,0.139869,0.182533,0.149751,0.109898,0.163142,0.130563,0.114888
877,1043.520,1044.510,1044.300,1045.710,1046.450,1048.210,1051.780,1052.950,1052.920,1055.280,...,0.274558,0.352880,0.208951,0.255684,0.264279,0.268425,0.232350,0.302300,0.247022,0.310537
531,1090.690,1088.890,1085.990,1086.160,1093.460,1101.950,1107.410,1110.360,1108.970,1112.110,...,0.490061,0.530606,0.476366,0.603870,0.536254,0.528459,0.533958,0.498837,0.447291,0.452878
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
847,1048.660,1048.410,1049.550,1051.870,1055.470,1060.520,1064.650,1069.380,1067.780,1063.160,...,0.286991,0.255365,0.279262,0.251752,0.255917,0.261745,0.343481,0.245168,0.223185,0.309518
715,990.450,991.807,995.156,998.132,998.969,999.495,999.234,1001.010,1002.630,1003.090,...,0.324027,0.321507,0.328478,0.341554,0.321462,0.309721,0.351771,0.374401,0.322821,0.365543
905,1051.730,1054.550,1054.650,1055.080,1054.370,1052.730,1050.940,1052.150,1053.420,1053.750,...,0.327440,0.213680,0.258504,0.253561,0.284979,0.230950,0.162257,0.276877,0.208838,0.196751
235,771.532,770.143,770.416,771.801,771.499,770.554,770.525,770.896,772.109,773.158,...,0.141098,0.125205,0.104226,0.128481,0.135601,0.139922,0.147997,0.110854,0.139768,0.150828
1061,767.083,768.121,769.065,766.442,766.802,771.188,773.595,776.006,775.431,774.287,...,0.273484,0.274416,0.274139,0.273391,0.274957,0.275049,0.273631,0.275163,0.275722,0.275414

In [13]:
clf = tree.DecisionTreeClassifier()
accuracy = cross_val_score(clf,X_train2,y_train2,scoring="accuracy",cv=10)
print(f"Accuracy for each cv is:{accuracy}")
print("---------------------------")
print(f"Mean accuracy is {np.mean(accuracy)}")

Accuracy for each cv is:[0.72727273 0.61038961 0.7012987  0.75324675 0.72368421 0.64
 0.77333333 0.72       0.72       0.70666667]
---------------------------
Mean accuracy is 0.7075892002734108

In [15]:
#Accuracy on test set
X_test2 = X_test.fillna(X_train.mean())
clf = tree.DecisionTreeClassifier(random_state = 1)
clf = clf.fit(X_train2,y_train)
y_pred = clf.predict(X_test2)
clf.score(X_test2,y_test)

0.6901840490797546

## Try data transformation

In [14]:
from sklearn.preprocessing import MinMaxScaler
X_train3 = MinMaxScaler().fit_transform(X_train2)
X_train3 = pd.DataFrame(X_train3)
X_train3

,0,1,2,3,4,5,6,7,8,9,...,3110,3111,3112,3113,3114,3115,3116,3117,3118,3119
0,0.664637,0.666694,0.670168,0.672848,0.672916,0.675464,0.674844,0.674289,0.670451,0.665065,...,0.249031,0.361014,0.380866,0.349353,0.220927,0.415656,0.357190,0.294320,0.317715,0.332814
1,0.690766,0.684188,0.676839,0.675154,0.674827,0.673587,0.668202,0.667577,0.673772,0.670466,...,0.370901,0.320409,0.334017,0.343727,0.182653,0.240506,0.301864,0.253783,0.441382,0.287404
2,0.209392,0.204327,0.197972,0.196487,0.193718,0.190718,0.178856,0.170240,0.163112,0.152105,...,0.063556,0.103433,0.123472,0.103061,0.128965,0.117910,0.010972,0.138572,0.088304,0.039901
3,0.673655,0.672754,0.669704,0.671798,0.672898,0.675929,0.679016,0.682553,0.681465,0.682390,...,0.277272,0.413539,0.209253,0.282452,0.261708,0.301019,0.209010,0.353287,0.267995,0.349591
4,0.754368,0.748947,0.741382,0.741414,0.753847,0.768467,0.775730,0.782639,0.779455,0.782041,...,0.625800,0.696342,0.621864,0.821774,0.703356,0.702241,0.696793,0.656536,0.577002,0.574901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
754,0.682450,0.679450,0.678730,0.682400,0.688430,0.697126,0.701391,0.711196,0.707444,0.696207,...,0.297380,0.258370,0.317740,0.276362,0.248130,0.290712,0.388740,0.265135,0.231216,0.347978
755,0.582846,0.582272,0.585210,0.589915,0.591139,0.592044,0.587663,0.592003,0.593544,0.590875,...,0.357277,0.363617,0.393678,0.415460,0.354565,0.364737,0.402147,0.464536,0.384950,0.436659
756,0.687703,0.689991,0.687498,0.687924,0.686536,0.683712,0.677556,0.681158,0.682339,0.679707,...,0.362797,0.192039,0.285711,0.279164,0.295322,0.243197,0.095651,0.314060,0.209079,0.169481
757,0.208250,0.201711,0.198812,0.200391,0.199447,0.197819,0.190047,0.190833,0.190530,0.187690,...,0.061431,0.051255,0.047667,0.085421,0.052754,0.102744,0.072588,0.057893,0.102507,0.096790
758,0.200638,0.198240,0.196490,0.191168,0.191359,0.198911,0.195384,0.199741,0.196338,0.189670,...,0.275534,0.288684,0.309836,0.309879,0.279048,0.311239,0.275773,0.311415,0.312278,0.293996

In [15]:
clf = tree.DecisionTreeClassifier()
accuracy = cross_val_score(clf,X_train3,y_train2,scoring="accuracy",cv=10)
print(f"Accuracy for each cv is:{accuracy}")
print("---------------------------")
print(f"Mean accuracy is {np.mean(accuracy)}")

Accuracy for each cv is:[0.75324675 0.67532468 0.72727273 0.72727273 0.80263158 0.69333333
 0.65333333 0.77333333 0.70666667 0.72      ]
---------------------------
Mean accuracy is 0.7232415128730918

In [18]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train, clf.predict(X_train3))

1.0

In [19]:
X_test3 = MinMaxScaler().transform(X_test2)
X_test3 = pd.DataFrame(X_test3)
#Predict the response for test dataset
clf = clf.fit(X_train3,y_train)
y_pred = clf.predict(X_test3)
clf.score(X_test3,y_test)

0.6687116564417178

In [20]:
#The behind mechanism of calculating the accuracy
result = 0
y_ravel_test = np.ravel(y_test)
for i in range(len(y_pred)):
    result += 1 if y_pred[i] == y_ravel_test[i] else 0

result/len(y_pred)

0.6687116564417178

## Try feature selection

In [277]:
#Using Recursive feature selection takes a lot time,so only 100 subset has been chosen.
from sklearn.feature_selection import RFE
clf = tree.DecisionTreeClassifier()
rfe = RFE(clf, 5)

fit = rfe.fit(X_train3.iloc[:,1:100], y_ravel_train)
print("Num Features: %s" % (fit.n_features_))
print("Selected Features: %s" % (fit.support_))
print("Feature Ranking: %s" % (fit.ranking_))

Num Features: 5
Selected Features: [ True False False False False False False  True False False False False
 False False False False False False False False False False False False
 False False False False  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False  True False False
 False  True False False False False False False False False False False
 False False False False False False False False False False False False
 False False False]
Feature Ranking: [ 1 46 44 39  4 40 41  1 47 37 36 38 22 25 71 32 13 12 69 86 49 76 18 61
  9 52 57  2  1 35  8 29 92 77 27 81 24 95 83 34 14 90 85 62 28 70 72 16
 84 21 56 10 51 30 58 23 48 50 66 15 42 65  3  5 68 33 31 67 55  1 74 17
  6  1 75 11 80 87 88 82 78 79 89  7 19 60 53 64 73 59 63 26 43 54 45 20
 91 93 94]

In [61]:
clf = tree.DecisionTreeClassifier()
from sklearn.feature_selection import SelectFromModel
clf = clf.fit(X_train2, y_train)
print(clf.feature_importances_) 

model = SelectFromModel(clf, prefit=True)
X_new = model.transform(X_train2)
print(X_new.shape)
          
X_new = pd.DataFrame(X_new)
X_new

[0.         0.01148115 0.         ... 0.         0.         0.        ]
(759, 47)

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
0,1040.980,1048.210,1045.400,2.39640,1493.240,89.0677,87.0357,11773.30,43.5985,55.5571,...,0.138961,0.029910,0.041499,0.398611,1.127010,0.525707,0.748041,0.124376,1.306080,0.924065
1,1051.170,1044.360,1048.480,2.00856,1499.200,85.2322,86.3882,11799.30,43.1446,52.8894,...,0.188287,0.107456,0.147825,0.395494,1.147040,0.502443,4.779780,0.168665,1.499650,0.687801
2,771.667,759.084,752.864,3.19598,796.505,88.6286,89.3512,7178.40,28.5607,72.7338,...,0.057312,0.070913,0.078952,0.358177,1.838670,0.558730,0.306591,0.062374,0.360451,0.335213
3,1044.510,1052.950,1055.280,1.79320,1503.830,86.4243,86.8763,11655.20,43.9165,54.1897,...,0.132286,0.039552,0.133599,0.464495,0.981831,0.593809,3.555490,0.135211,1.451980,0.708772
4,1088.890,1110.360,1112.110,2.95138,1321.350,100.9900,100.6160,10804.30,51.8505,55.6509,...,0.116522,0.059812,0.007751,0.487318,0.782934,0.501373,0.387277,0.115590,1.810530,1.850610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
754,1048.410,1069.380,1063.160,2.12109,1494.750,87.2262,84.9667,11661.30,44.2314,53.9895,...,0.085068,0.074101,0.101024,0.260952,0.897830,0.479526,0.955795,0.277727,1.321180,0.802134
755,991.807,1001.010,1003.090,2.70013,1497.600,88.5424,91.7063,11859.40,43.9677,54.9723,...,0.116429,0.080860,0.034841,0.278878,0.935954,0.466736,0.820834,0.175354,1.244570,1.097200
756,1054.550,1052.150,1053.750,2.43673,1491.620,84.3601,88.2387,11695.70,43.4908,53.5110,...,0.167626,0.050516,0.166870,0.410751,0.941551,0.512803,4.710440,0.176096,1.329350,0.687430
757,770.143,770.896,773.158,3.13545,791.810,81.1821,80.3216,7194.76,27.1871,59.1419,...,0.063765,0.065507,0.072241,0.211466,2.138310,0.633702,0.178575,0.095956,0.356263,0.220855
758,768.121,776.006,774.287,2.64981,1263.970,75.9026,75.4108,14037.60,28.8667,52.1917,...,0.043461,0.010562,0.044439,0.231504,0.467252,0.600565,0.168801,0.082577,0.500636,0.474931

In [62]:
top_5_feature = clf.feature_importances_.argsort()[-5:][::-1]
top_5_feature

array([180, 480,   9, 701, 274])

In [63]:
X_new1 = X_train2[top_5_feature]
X_new1

           180       480       9         701       274
776    89.0677   80.8366  1045.400  104.1130  11773.30
891    85.2322   61.6618  1048.480  103.7210  11799.30
107    88.6286  123.8350   752.864  106.0250   7178.40
877    86.4243   64.3092  1055.280  103.1380  11655.20
531   100.9900   55.0120  1112.110  120.4600  10804.30
...        ...       ...       ...       ...       ...
847    87.2262   69.6511  1063.160  101.9480  11661.30
715    88.5424   74.6098  1003.090   96.2577  11859.40
905    84.3601   59.1863  1053.750  105.7640  11695.70
235    81.1821   52.5588   773.158  100.6600   7194.76
1061   75.9026   26.8120   774.287   80.1887  14037.60

[759 rows x 5 columns]

In [65]:
clf = tree.DecisionTreeClassifier()
accuracy = cross_val_score(clf,X_new1,y_train,scoring="accuracy",cv=10)
print(f"Accuracy for each cv is:{accuracy}")
print("---------------------------")
print(f"Mean accuracy is {np.mean(accuracy)}")

Accuracy for each cv is:[0.75324675 0.77922078 0.72727273 0.80519481 0.80263158 0.77333333
 0.73333333 0.73333333 0.64       0.76      ]
---------------------------
Mean accuracy is 0.7507566643882433

In [66]:
clf = tree.DecisionTreeClassifier()
model = clf.fit(X_new1,y_train)
clf.score(X_new1,y_train)

1.0

In [68]:
clf = tree.DecisionTreeClassifier()
model = clf.fit(X_new1,y_train)
clf.score(X_test2[top_5_feature],y_test)

0.7177914110429447

## Naive Bayes

In [75]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
model = GaussianNB()

# Train the model using the training sets
model.fit(X_train2,y_train)

print(f"training accuracy : {model.score(X_train2,y_train)}")
print("-------------")
print("Test accuracy: ", model.score(X_test2,y_test

training accuracy : 0.6679841897233202
-------------
Test accuracy:  0.6411042944785276

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [80]:
model = GaussianNB()
model.fit(X_train1,y_train)

print(model.score(X_train1,y_train))
model.score(X_test1,y_test)

0.6719367588932806

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.6073619631901841

In [82]:
model.fit(X_train3,y_train)
print(model.score(X_train3,y_train))
model.score(X_test3,y_test)

0.6706192358366272

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.6380368098159509

In [129]:
from sklearn.decomposition import PCA
result = 0
y_test_ravel = np.ravel(y_test)
y_train_ravel = np.ravel(y_train)
for n in range(1,100):
    pca=PCA(n)
    pca.fit(X_train3)
    X_pca_train = pd.DataFrame(pca.transform(X_train3))
    pca.fit(X_test3)
    X_pca_test = pd.DataFrame(pca.transform(X_test3))
    model.fit(X_pca_train,y_train_ravel)
    score = model.score(X_pca_test,y_test_ravel)
    if score > result:
        result = score
        print(n)
print(result)

1
6
0.6595092024539877

In [107]:
pca.fit(X_test3)
X_pca_test = pd.DataFrame(pca.transform(X_test3))
X_pca_test

,0,1,2,3,4,5,6,7,8,9
0,-5.818018,-1.387499,-1.844431,-2.765670,-1.102708,0.418567,0.472509,0.645052,-0.183958,-0.141327
1,13.340022,-0.933529,-0.124724,0.071006,0.033922,-0.474458,-0.787188,0.657198,-0.193750,0.387915
2,-5.605667,-3.097059,-3.640884,4.776380,0.422109,0.095362,0.227619,0.641048,0.068177,-0.900289
3,-4.497749,-3.457648,6.436092,0.905046,1.046244,0.308417,0.628963,0.094387,0.701642,0.278102
4,12.653668,0.141004,-0.667247,-0.279784,-0.909185,-0.914026,0.792252,0.740140,0.855632,0.018709
...,...,...,...,...,...,...,...,...,...,...
321,-4.097430,-1.412644,3.378174,0.154598,-1.735335,-0.234647,-1.419613,-0.842452,1.318821,-0.415361
322,-5.740231,-1.558082,-1.947143,-2.530410,-0.596036,0.001214,0.319486,-0.045425,-0.612205,-0.029739
323,-3.413564,11.447195,0.379819,0.915244,-0.081747,0.000186,-0.383613,-0.223139,0.125282,0.072258
324,-5.874924,-3.451158,-4.151140,5.147972,0.028232,0.157113,0.031749,-0.038658,-0.250965,-0.353641
325,-5.385538,-1.006248,-1.994148,-2.827887,1.893044,-0.991469,-0.334302,0.540360,0.236330,-0.120766

In [108]:
model.fit(X_pca_train,y_train)
print(model.score(X_pca_train,y_train))
model.score(X_pca_test,y_test)

0.7206851119894598

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.6595092024539877